version: '3.11'
services:
  dbpostgres:
    image: postgres
    environment:
      - POSTGRES_DB=railway
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iCvDaIoaZmSMGfHhZesEgnbWjunkffef
      - POSTGRES_HOST=viaduct.proxy.rlwy.net
      - POSTGRES_PORT=54519
  docicpdfbackend:
    container_name: PFE_APP
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - dbpostgres
