name: Django CI/CD with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: railway
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: iCvDaIoaZmSMGfHhZesEgnbWjunkffef
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker images
        run: docker-compose build

      - name: Run Docker Compose (with database)
        run: docker-compose up -d

      - name: Wait for PostgreSQL to be ready
        run: |
          until docker-compose exec dbpostgres pg_isready -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done

      - name: Run Django migrations
        run: docker-compose exec PFE_APP python manage.py migrate

      - name: Run Django tests
        run: docker-compose exec PFE_APP python manage.py test

      - name: Shut down Docker Compose
        run: docker-compose down
name: Django CI/CD with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: railway
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: iCvDaIoaZmSMGfHhZesEgnbWjunkffef
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker images
        run: docker-compose build

      - name: Run Docker Compose (with database)
        run: docker-compose up -d

      - name: Wait for PostgreSQL to be ready
        run: |
          until docker-compose exec dbpostgres pg_isready -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done

      - name: Run Django migrations
        run: docker-compose exec PFE_APP python manage.py migrate

      - name: Run Django tests
        run: docker-compose exec PFE_APP python manage.py test

      - name: Shut down Docker Compose
        run: docker-compose down
name: Django CI/CD with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: railway
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: iCvDaIoaZmSMGfHhZesEgnbWjunkffef
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker images
        run: docker-compose build

      - name: Run Docker Compose (with database)
        run: docker-compose up -d

      - name: Wait for PostgreSQL to be ready
        run: |
          until docker-compose exec dbpostgres pg_isready -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done

      - name: Run Django migrations
        run: docker-compose exec PFE_APP python manage.py migrate

      - name: Run Django tests
        run: docker-compose exec PFE_APP python manage.py test

      - name: Shut down Docker Compose
        run: docker-compose down
name: Django CI/CD with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: railway
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: iCvDaIoaZmSMGfHhZesEgnbWjunkffef
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker images
        run: docker-compose build

      - name: Run Docker Compose (with database)
        run: docker-compose up -d

      - name: Wait for PostgreSQL to be ready
        run: |
          until docker-compose exec dbpostgres pg_isready -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done

      - name: Run Django migrations
        run: docker-compose exec PFE_APP python manage.py migrate

      - name: Run Django tests
        run: docker-compose exec PFE_APP python manage.py test

      - name: Shut down Docker Compose
        run: docker-compose down
name: Django CI/CD with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: railway
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: iCvDaIoaZmSMGfHhZesEgnbWjunkffef
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker images
        run: docker-compose build

      - name: Run Docker Compose (with database)
        run: docker-compose up -d

      - name: Wait for PostgreSQL to be ready
        run: |
          until docker-compose exec dbpostgres pg_isready -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done

      - name: Run Django migrations
        run: docker-compose exec PFE_APP python manage.py migrate

      - name: Run Django tests
        run: docker-compose exec PFE_APP python manage.py test

      - name: Shut down Docker Compose
        run: docker-compose down
