version: '3.8'
services:
  traitmentpdfapi:
    container_name: PFE_APP
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: ["sh" , "./start.sh"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres_db

  postgres_db:
    container_name: databasepfe
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${SQL_NAME}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}

volumes:
  postgres_data:
