# Generated by Django 5.0.4 on 2024-06-07 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('total_pages', models.IntegerField(default=0)),
                ('categorie', models.CharField(max_length=255)),
                ('etat', models.CharField(choices=[('traité', 'Traité'), ('non_traité', 'Non traité')], default='non_traité', max_length=20)),
                ('patient_associé', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numéro', models.IntegerField()),
                ('orientation', models.CharField(max_length=50)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_pages', to='gestionpdf.pdf')),
            ],
        ),
    ]
