# Generated by Django 5.0.4 on 2024-06-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpdf', '0002_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
