# Generated by Django 5.0.4 on 2024-06-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpdf', '0003_pdf_date_modification'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
