# Generated by Django 5.0.4 on 2024-06-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpdf', '0005_pdf_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='modified_file',
            field=models.FileField(blank=True, null=True, upload_to='modified_pdfs/'),
        ),
    ]
