# Generated by Django 5.0.4 on 2024-07-04 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpdf', '0006_pdf_modified_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='modified_file',
        ),
        migrations.CreateModel(
            name='ModifiedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_file', models.FileField(upload_to='modified_pdfs/')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_pdf', to='gestionpdf.pdf')),
            ],
        ),
    ]
