# Generated by Django 5.0.4 on 2024-07-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpdf', '0008_remove_pdf_image_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModifiedPDF',
        ),
    ]
