# Generated by Django 5.0.4 on 2024-07-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpdf', '0009_delete_modifiedpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
