# Generated by Django 5.0.4 on 2024-07-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpdf', '0010_pdf_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='image',
        ),
        migrations.AddField(
            model_name='pdf',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='pdfs', to='gestionpdf.image'),
        ),
    ]
