# Generated by Django 5.0.4 on 2024-07-06 21:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpdf', '0011_remove_pdf_image_pdf_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='signature',
        ),
        migrations.AddField(
            model_name='pdf',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='date_modification',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
