# Generated by Django 5.0.4 on 2024-07-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpdf', '0014_alter_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='pdfs/'),
        ),
    ]
