# Generated by Django 5.0.4 on 2024-08-09 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpdf', '0015_alter_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='page_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='image',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_files', to='gestionpdf.pdf'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='images/png/'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='images',
            field=models.ManyToManyField(related_name='pdfs', to='gestionpdf.image'),
        ),
    ]
