# Generated by Django 5.0.4 on 2024-08-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpdf', '0016_image_page_number_image_pdf_alter_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='filtered_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
