# Generated by Django 5.0.4 on 2024-09-02 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpdf', '0017_pdf_filtered_text_alter_pdf_date_modification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='extracted_images/')),
                ('page_number', models.IntegerField()),
                ('crop_coordinates', models.JSONField()),
                ('date_extraction', models.DateTimeField(auto_now_add=True)),
                ('pdf_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_images', to='gestionpdf.pdf')),
            ],
        ),
    ]
