# Generated by Django 5.0.4 on 2024-09-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpdf', '0018_extractedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedimage',
            name='crop_coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
