# Generated by Django 5.0.4 on 2024-09-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpdf', '0019_alter_extractedimage_crop_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='pdfs', to='gestionpdf.image'),
        ),
    ]
