name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.5.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Set up environment variables
        run: |
          echo "POSTGRES_USER=postgres" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=iCvDaIoaZmSMGfHhZesEgnbWjunkffef" >> $GITHUB_ENV
          echo "POSTGRES_DB=railway" >> $GITHUB_ENV
          echo "POSTGRES_HOST=viaduct.proxy.rlwy.net" >> $GITHUB_ENV
          echo "POSTGRES_PORT=54519" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: |
          pip install -r docicpdfbackend/requirements.txt  # Chemin vers requirements.txt

      - name: Run Django Migrations
        run: |
          cd docicpdfbackend
          python manage.py migrate

      - name: Run Tests
        run: |
          cd docicpdfbackend
          python manage.py test
