name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: railway
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: iCvDaIoaZmSMGfHhZesEgnbWjunkffef
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.5.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build and Run Docker Compose
        run: |
          docker-compose -f ./docicpdfbackend/docker-compose.yaml up -d --build
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: iCvDaIoaZmSMGfHhZesEgnbWjunkffef
          POSTGRES_DB: railway

      - name: Wait for DB to be ready
        run: |
          docker-compose exec postgres pg_isready -U postgres -d railway

      - name: Run Django Migrations
        run: |
          docker-compose exec docicpdfbackend python manage.py migrate

      - name: Run Tests
        run: |
          docker-compose exec docicpdfbackend python manage.py test

      - name: Shut down services
        run: |
          docker-compose down
