name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: docicdb
          POSTGRES_USER: eya
          POSTGRES_PASSWORD: eya
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U eya"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Run Docker Compose
        run: |
          docker-compose up 
        env:
          POSTGRES_USER: eya
          POSTGRES_PASSWORD: eya
          POSTGRES_DB: docicdb

      - name: Run Django Migrations
        run: |
          docker-compose exec pfeapp python manage.py migrate

      - name: Run Tests
        run: |
          docker-compose exec pfeapp python manage.py test

      - name: Shut down services
        run: |
          docker-compose down
